apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: yf23yl84w-go-gitops
  description: This is GitOps manifest for yf23yl84w-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=yf23yl84w-go
    backstage.io/kubernetes-id: yf23yl84w-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: yf23yl84w-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:yf23yl84w-go
