apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yf23yl84w-go
  janus-idp.io/tekton: yf23yl84w-go
  backstage.io/kubernetes-id: yf23yl84w-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: yf23yl84w-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
